/// User model representing user data from the Django backend.
///
/// This model matches the Django CustomUser model structure and handles
/// JSON serialization/deserialization for API communication.
///
/// All date/time fields are automatically parsed from ISO 8601 strings.
class User {
  /// Unique user identifier (auto-generated by backend)
  final String? id;

  /// User's first name
  final String firstName;

  /// User's last name
  final String lastName;

  /// User's email address (unique)
  final String email;

  /// Optional username (unique if provided)
  final String? username;

  /// Optional phone number (unique if provided)
  final String? phoneNumber;

  /// Whether the user account is active
  final bool isActive;

  /// Whether the user has staff privileges
  final bool isStaff;

  /// When the user account was created
  final DateTime? dateJoined;

  User({
    this.id,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.username,
    this.phoneNumber,
    this.isActive = true,
    this.isStaff = false,
    this.dateJoined,
  });

  /// Returns the user's full name by combining first and last names
  String get fullName => '$firstName $lastName';

  /// Creates a User instance from JSON data (typically from API responses)
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id']?.toString(),
      firstName: json['first_name'] ?? '',
      lastName: json['last_name'] ?? '',
      email: json['email'] ?? '',
      username: json['username'],
      phoneNumber: json['phone_number'],
      isActive: json['is_active'] ?? true,
      isStaff: json['is_staff'] ?? false,
      dateJoined: json['date_joined'] != null
          ? DateTime.parse(json['date_joined'])
          : null,
    );
  }

  /// Converts the User instance to JSON format for API requests
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'first_name': firstName,
      'last_name': lastName,
      'email': email,
      'username': username,
      'phone_number': phoneNumber,
      'is_active': isActive,
      'is_staff': isStaff,
      'date_joined': dateJoined?.toIso8601String(),
    };
  }

  /// Creates a copy of this User with some values optionally overridden
  User copyWith({
    String? id,
    String? firstName,
    String? lastName,
    String? email,
    String? username,
    String? phoneNumber,
    bool? isActive,
    bool? isStaff,
    DateTime? dateJoined,
  }) {
    return User(
      id: id ?? this.id,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      email: email ?? this.email,
      username: username ?? this.username,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      isActive: isActive ?? this.isActive,
      isStaff: isStaff ?? this.isStaff,
      dateJoined: dateJoined ?? this.dateJoined,
    );
  }
}
